name: release

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    tags: ["*"]
    paths-ignore: ['**.md']

permissions:
  contents: write

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          export NEXT_VERSION=${{ steps.taggerDryRun.outputs.new_tag }}
          echo "The next tag version will be: $NEXT_VERSION"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"    
      - name: Install dependencies
        run: dotnet restore
      - name: Compile
        run: ./build-with-version.sh $NEXT_VERSION
      - name: Build
        run: |
          ./publish-release.sh linux x64
          ./publish-release.sh linux arm64
          ./publish-release.sh osx x64
          ./publish-release.sh win x64
      - name: Rename
        run: |
          mv ./release/linux/DotNetAstGen dotnetastgen-linux
          mv ./release/linux-arm/DotNetAstGen dotnetastgen-linux-arm64
          mv ./release/macos/DotNetAstGen dotnetastgen-macos
          mv ./release/win/DotNetAstGen.exe dotnetastgen-win.exe
      - name: Make executable
        run: |
          chmod +x dotnetastgen-linux-arm64
          chmod +x dotnetastgen-macos
      - name: Set next release version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          files: |
            dotnetastgen-linux
            dotnetastgen-linux-arm64
            dotnetastgen-macos
            dotnetastgen-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
